import { z } from 'zod';
import { LIMITS } from '../constants';

/** Entity ids are UUIDs generated by the database. */
export const idSchema = z.uuid({ message: 'Invalid id' });

/** Tag names: letters, numbers, "-" and "_", stored lower-case. Shared by /tags and task payloads. */
export const tagNameSchema = z
  .string()
  .trim()
  .toLowerCase()
  .min(1, 'Name is required')
  .max(40)
  .regex(/^[\p{L}\p{N}_-]+$/u, 'Tags can use letters, numbers, - or _');

export const hexColorSchema = z
  .string()
  .trim()
  .regex(/^#[0-9a-fA-F]{6}$/, 'Colour must be a hex value like #6366f1');

/** ISO-8601 timestamp with offset, e.g. 2026-09-23T10:00:00.000Z. */
export const isoDateTimeSchema = z.iso.datetime({ offset: true });

/** Accept a single value or repeated query parameter / comma list and normalise to an array. */
export const csvArray = <T extends z.ZodType>(item: T) =>
  z.preprocess((v) => {
    if (v === undefined || v === null || v === '') return undefined;
    const arr = Array.isArray(v) ? v : [v];
    return arr.flatMap((x) => String(x).split(',')).map((s) => s.trim()).filter(Boolean);
  }, z.array(item).max(20).optional());

export const paginationQuerySchema = z.object({
  cursor: z.string().max(200).optional(),
  limit: z.coerce.number().int().min(1).max(LIMITS.pageSizeMax).default(LIMITS.pageSizeDefault),
});

export interface Page<T> {
  items: T[];
  nextCursor: string | null;
}

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    details?: Array<{ path: string; message: string }>;
    requestId?: string;
  };
}
